export const getVendorCategoryInKorean = (category) => {
  const categoryMap = {
    COOKING: '요리',
    BAKING: '베이킹',
    CRAFT: '공예',
    ART: '미술',
    MUSIC: '음악',
    DANCE: '댄스',
    FITNESS: '피트니스',
    BEAUTY: '뷰티',
    PHOTOGRAPHY: '사진',
    LANGUAGE: '언어',
    COMPUTER: '컴퓨터',
    HOBBY: '취미',
    EDUCATION: '교육',
    LIFESTYLE: '라이프스타일',
    BUSINESS: '비즈니스',
    HEALTH: '건강',
    FASHION: '패션',
    GARDENING: '원예',
    PET: '반려동물',
    TRAVEL: '여행',
    SPORTS: '스포츠',
    GAME: '게임',
    MEDITATION: '명상',
    YOGA: '요가',
    WINE: '와인',
    COFFEE: '커피',
    TEA: '차',
    FLOWER: '플라워',
    CANDLE: '캔들',
    SOAP: '비누',
    PERFUME: '향수',
    JEWELRY: '쥬얼리',
    LEATHER: '가죽공예',
    WOOD: '목공예',
    CERAMIC: '도예',
    PAINTING: '페인팅',
    DRAWING: '드로잉',
    CALLIGRAPHY: '서예',
    KNITTING: '뜨개질',
    SEWING: '재봉',
    EMBROIDERY: '자수',
    ORIGAMI: '종이접기',
    MAKEUP: '메이크업',
    NAIL: '네일아트',
    HAIR: '헤어',
    SKINCARE: '스킨케어',
  };

  return categoryMap[category] || category;
};
